apiVersion: v1
kind: Pod
metadata:
  name: backup-pod
spec:
  containers:
  - name: backup-container
    image: your-backup-image:tag
    volumeMounts:
    - name: data-volume
      mountPath: /data  # Mount the PVC at this path inside the container
    # Add additional container configuration here if needed
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: data-pvc  # Name of the PersistentVolumeClaim to mount